# Numpy

In [1]:
import numpy as np

In [3]:
# Toda operacion que se haga con np.array te regresa un arreglo
vector = np. array([0, 1, 2, 3, 4, 5])
print(vector)

[0 1 2 3 4 5]


In [13]:
vectorDos = np.array([1, 2, 3, 4, 5], dtype = np.float32)
print(vectorDos)

vector.dtype = np.float16
print(vector)

vectorTres = np.array([1, 2, 3, 4, 5])
vectorTres = vectorTres.astype(np.float32)
print(vectorTres)

[1. 2. 3. 4. 5.]
[0.0e+00 0.0e+00 6.0e-08 0.0e+00 1.2e-07 0.0e+00 1.8e-07 0.0e+00 2.4e-07
 0.0e+00 3.0e-07 0.0e+00]
[1. 2. 3. 4. 5.]


In [14]:
#Acceso a los elementos en vectores uni... eso
print(vectorTres[3])

4.0


In [18]:
#Tomar segmento de un vector. Slicing
vectorCuatro = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(vectorCuatro[0:8:2])

[0 2 4 6]


In [28]:
# OJO CON ESTO PAO: Operaciones de Vectores  (Y checar de paso las de matrices)
a = np.array([0,1,2])
b = np.array([0,-1,-3])
c = np.array([1,1,1])
print(a + b)
print(a - b)
print(a * b)
print(a / c)
print(2 * a)
demo = a >= 1
print(demo) #Evaluo elemento por elemento y regreso un boolean
print(a ** a)


[ 0  0 -1]
[0 2 5]
[ 0 -1 -6]
[0. 1. 2.]
[0 2 4]
[False  True  True]
[1 1 4]


### Divición de la recta
Rutinas linspace,arange para generar numeros entre un rango entre dos numeros dados. a<=x<=b -->linspace a<=x<b -->arange
    
    
Tanto la función linspace como la función arange se utilizan para generar secuencias numéricas en Python, pero difieren en la forma en que generan los valores de la secuencia. La diferencia principal entre ambas:

linspace: La función linspace (que significa "espacio lineal") genera una secuencia de números igualmente espaciados en un rango dado. Toma tres argumentos: el valor inicial, el valor final y el número de elementos que se desean generar. La función devuelve un arreglo NumPy con los valores distribuidos uniformemente entre el valor inicial y el valor final, incluyendo ambos extremos. La diferencia entre los valores consecutivos es constante.

arange: La función arange genera una secuencia de números en un rango dado con un paso especificado. Toma hasta tres argumentos: el valor inicial (opcional), el valor final y el paso (opcional). La función devuelve un arreglo NumPy con los valores generados. La diferencia entre los valores consecutivos puede ser no uniforme si se especifica un paso no entero.

In [43]:
# Divición de la recta
# En Linspace:
#1: Num Inicio, 2: Num limite, 3:En cuantos segmentos se divide

print(np.linspace(0,15,15))
print()
print(np.arange(0,16,1))

[ 0.          1.07142857  2.14285714  3.21428571  4.28571429  5.35714286
  6.42857143  7.5         8.57142857  9.64285714 10.71428571 11.78571429
 12.85714286 13.92857143 15.        ]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [65]:
#Redimencionamiento con Shape

matrix = np.array([[1,2,3], [4,5,6], [7,8,3]])
a = np.arange(0,16,1)

print(matrix)
print()
print(matrix.shape)
print(a.shape)
print()

nueva = matrix.reshape(9,)
print(nueva)
print(matrix)
print()

b = a.reshape(4,4)
print(b)
print()

#ESTO QUE? No entendí
mt1=[[34,3],[67,7]]
mt2=[[11,2],[78,3]]
mt3=[[23,32],[90,1]]
arr1=np.array([mt1,mt2,mt3])

[[1 2 3]
 [4 5 6]
 [7 8 3]]

(3, 3)
(16,)

[1 2 3 4 5 6 7 8 3]
[[1 2 3]
 [4 5 6]
 [7 8 3]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



### Indexación con cortes
#### Matrices

Filas, columnas, de cuanto en cuanto

matriz[  inicio_fila  :  fin_fila  :  paso_fila,      inicio_columna  :  fin_columna  :  paso_columna]

In [64]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(m)
print(m.shape)

print("--------Corte---------")
c1 = m[:2, 1:3]
c2 = m[2:, :]
print(c2.shape)
print(c2[0][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
--------Corte---------
(1, 3)
8


### Sistema de Ecuaciones

Gráficamente la solución de un sistema de ecuaciones es la intersección de dos rectas.

In [72]:
A = np.array([[2,-1], [1,3]])
b = np.array([3,5])
c = np.linalg.solve(A,b)
print(c)
print()
print(A)
print()

# @ = Multiplicación de matrices
print("-------Multiplicación de Matrices--------")
print(A@c)

[2. 1.]

[[ 2 -1]
 [ 1  3]]

-------Multiplicación de Matrices--------
[3. 5.]
