In [1]:
import numpy as np

#### Ejercicio 1

In [15]:
A = np.array([[1,4], [-1,3], [2,-9]])
cero = np.zeros((3,2))
print("Matriz A")
print(A)
print("\nMatriz Cero")
print(cero)

print("\n---------------------------------\n")

print("a. A + O = A − O = A")
r = A + cero
print(r)

print("\nb. A − A = O")
r = A - A
print(r)

Matriz A
[[ 1  4]
 [-1  3]
 [ 2 -9]]

Matriz Cero
[[0. 0.]
 [0. 0.]
 [0. 0.]]

---------------------------------

a. A + O = A − O = A
[[ 1.  4.]
 [-1.  3.]
 [ 2. -9.]]

b. A − A = O
[[0 0]
 [0 0]
 [0 0]]


#### Ejercicio 2

In [28]:
A = np.array([[3,0], [-1,5]])
B = np.array([[4,-2,1], [0,2,3]])

print("Matriz A")
print(A)
print("\nMatriz B")
print(B)

print("\n------A+3B------")
b = (3*B)
#r = A + b
print("A+3B no se puede realizar, pues su numero de columnas no coinciden (2,2) (2,3) ")

print("\n------AB------")
r = A@B
print(r)

print("\n------A^3------")
r = A**3
print(r)

print("\n------B^2------")
r = B**2
print(r)

print("\n------(5A)B------")
r = (5*A)@B
print(r)

Matriz A
[[ 3  0]
 [-1  5]]

Matriz B
[[ 4 -2  1]
 [ 0  2  3]]

------A+3B------
A+3B no se puede realizar, pues su numero de columnas no coinciden (2,2) (2,3) 

------AB------
[[12 -6  3]
 [-4 12 14]]

------A^3------
[[ 27   0]
 [ -1 125]]

------B^2------
[[16  4  1]
 [ 0  4  9]]

------(5A)B------
[[ 60 -30  15]
 [-20  60  70]]


#### Ejercicio 3

Dos restaurantes desean comprar frutas para la siguiente semana. La tabla 1 muestra que tipo de fruta y cantidad desean adquirir. Se tienen dos centros comerciales, la tabla 2 muestra sus precios. ¿Cuánto costara comprar las frutas para cada uno de los centros comerciales?

In [34]:
rest=np.array([[30,15,4],[25,18,8]])
cent_com=np.array([[1.2,2.2,4.5],[1.3,2.1,4.6]])
t_cent_com = cent_com.T

print("Tabla1: Matriz Restaurante")
print(rest)
print("Tabla2 Transpuesta: Matriz Centro Comerc.")
print(t_cent_com)

costoTienda=rest@t_cent_com
print("\n\nResultado:")
print(costoTienda)
print("------------------------------------")
print("Centro comercial 1: $", (costoTienda[0,0]+costoTienda[1,0]))
print("Centro comercial 2: $", (costoTienda[0,1]+costoTienda[1,1]))


Tabla1: Matriz Restaurante
[[30 15  4]
 [25 18  8]]
Tabla2 Transpuesta: Matriz Centro Comerc.
[[1.2 1.3]
 [2.2 2.1]
 [4.5 4.6]]


Resultado:
[[ 87.   88.9]
 [105.6 107.1]]
------------------------------------
Centro comercial 1: $ 192.6
Centro comercial 2: $ 196.0


#### Ejercicio 4

Una fábrica elabora tres productos (escobas, escobetas, cepillos) y los envía a dos almacenes para su cuidado. El número de unidades esta dado en la tabla 3.

El costo de embarcar por camión es por cada unidad de escoba es 1.50, escobetas 1.00 y cepillos 2.00, el costo por tren es escoba es 1.75, escobetas 1.50 y cepillos 1.00. Organizar la información en una matriz, para ocupar la multiplicación de matrices, dependiendo de los resultados, indica que le conviene a la empresa embarcar con camión o tren.

In [46]:
prod_almac=np.array([[200,75],[150,100],[100,125]])
cam_tren=np.array([[1.5,1.0,2.0], [1.75,1.5,1.0]])


print("----Productos----")
print(prod_almac)
print("\n----Precios Camion y Tren----\n(Renglon0 = Camion, Renglon1 = Tren)")
print(cam_tren)

result = cam_tren@prod_almac
print("\n----Resultado----")
print(result)

print("\nEntonces:")
print("Camion: $", (result[0,0]+result[0,1]))
print("Tren: $", (result[1,0]+result[1,1]))
print("\nConviene en Tren")

----Productos----
[[200  75]
 [150 100]
 [100 125]]

----Precios Camion y Tren----
(Renglon0 = Camion, Renglon1 = Tren)
[[1.5  1.   2.  ]
 [1.75 1.5  1.  ]]

----Resultado----
[[650.   462.5 ]
 [675.   406.25]]

Entonces:
Camion: $ 1112.5
Tren: $ 1081.25

Conviene en Tren


#### Ejercicio 5

Resolver el siguiente sistema de ecuaciones:

In [109]:
mat1 = np.array([[3,2,6],[6,4,-9]])
mat2 = np.array([[1,1,3],[1,-4,1]])
mat3 = np.array([[2,-1,2,3],[2,3,-1,0],[1,2,2,-12]])


print("Primer Sistema de Ecuaciones")
print(mat1)

#Operaciones en la 1ra Matriz 
#Se realizan Slicings en la matriz para operar con vectores
b1 = mat1[0:1:, ::] 
#print(b1)
b2 = mat1[1:2:, ::]
#print(b2)
elim = -2
op = (elim*b1) + b2
#print(op)

print("Resultado: El sistema no tiene solución")
print(op)
print("-------------------------------------------")




print("\nSegundo Sistema de Ecuaciones")
print(mat2)

#Operaciones en la 2da Matriz 
#Se realizan Slicings en la matriz para operar con vectores
b1 = mat2[0:1:, ::] 
#print(b1)
b2 = mat2[1:2:, ::]
#print(b2)
elim = -1
op = (elim*b1) + b2
#print(op)
y = op[0,2]/op[0,1]
#print(y)
x = (b1[0,2] - (y * b1[0,1])) / b2[0,0]
#print(x)

print(f"Resultado: \nx = {x}  y   y = {y}")
print("-------------------------------------------")




print("\nTercer Sistema de Ecuaciones")
print(mat3)

#Operaciones en la 3ra Matriz 
#Esta vez se empleará el comando np.linalg.solve() para resolver un sistema de ecuaciones lineales
#Entonces:
mat = mat3[::, :3:] 
#print(mat)
sol = np.array([3,0,-12])
#print(sol)
sistema3 = np.linalg.solve(mat,sol)
#print(sistema3)


print(f"Resultado: \nx = {sistema3[0]},   y = {sistema3[1]}   y   z={sistema3[2]}")


Primer Sistema de Ecuaciones
[[ 3  2  6]
 [ 6  4 -9]]
Resultado: El sistema no tiene solución
[[  0   0 -21]]
-------------------------------------------

Segundo Sistema de Ecuaciones
[[ 1  1  3]
 [ 1 -4  1]]
Resultado: 
x = 2.6  y   y = 0.4
-------------------------------------------

Tercer Sistema de Ecuaciones
[[  2  -1   2   3]
 [  2   3  -1   0]
 [  1   2   2 -12]]
Resultado: 
x = 3.6521739130434785,   y = -3.782608695652174   y   z=-4.043478260869565
